version: '3.7'
services:
    postgres:
        image: postgres:15.3
        privileged: true
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=lfo_db
          - PGDATA=/var/lib/pg_data
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
